from tools.web_search import web_search_tool, duckduckgo_search_tool
from tools.arxiv_search import arxiv_search_tool, arxiv_download_tool
from tools.code_executor import execute_python_tool, analyze_data_tool
